disabled = false
languageCode = "zh-cn"
languageName = "Simplified Chinese (China)"
weight = 1
title = "Vortex's World"

[params]
displayName = "简体中文"
isoCode = "cn"
rtl = false
dateFormat = "2 January 2006"
# logo = "img/logo.png"
# secondaryLogo = "img/secondary-logo.png"
description = "My awesome website"
copyright = "Copy, _right?_ :thinking_face:"

[params.author]
name = "Welcome to Vortex's World"
email = "zhugeshi8@gmail.com"
#   image = "img/blowfish_logo.png"
#   imageQuality = 96
headline = "I'm only human"
bio = "A little bit about you"
links = [
    { github = "https://github.com/zhugeshi" },
    { email = "zhugeshi8@gmail.com" },
]
